name: Print Directories and Files

on: 
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List directories and files
      run: |
        echo "Listing all directories and files:"
        find . -type f -print
